// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfNlSREc2jeesDDW0Zyuza0yUUaHRBXK0',
    appId: '1:2292329684:web:3b6b82a2d2750913ac5f41',
    messagingSenderId: '2292329684',
    projectId: 'alertme-a5605',
    authDomain: 'alertme-a5605.firebaseapp.com',
    storageBucket: 'alertme-a5605.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQoQ1YbffRC0xs1Xt4aLDaJvnwn-EIRJw',
    appId: '1:2292329684:android:a8ab52f4c3c30f5eac5f41',
    messagingSenderId: '2292329684',
    projectId: 'alertme-a5605',
    storageBucket: 'alertme-a5605.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7f98MNEIkAbpTZzo-YoDRSsPsY0Ew_r4',
    appId: '1:2292329684:ios:01f9bf56ae3487abac5f41',
    messagingSenderId: '2292329684',
    projectId: 'alertme-a5605',
    storageBucket: 'alertme-a5605.firebasestorage.app',
    iosBundleId: 'com.example.alertme',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7f98MNEIkAbpTZzo-YoDRSsPsY0Ew_r4',
    appId: '1:2292329684:ios:01f9bf56ae3487abac5f41',
    messagingSenderId: '2292329684',
    projectId: 'alertme-a5605',
    storageBucket: 'alertme-a5605.firebasestorage.app',
    iosBundleId: 'com.example.alertme',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfNlSREc2jeesDDW0Zyuza0yUUaHRBXK0',
    appId: '1:2292329684:web:06786eb224dd6dedac5f41',
    messagingSenderId: '2292329684',
    projectId: 'alertme-a5605',
    authDomain: 'alertme-a5605.firebaseapp.com',
    storageBucket: 'alertme-a5605.firebasestorage.app',
  );
}
